apiVersion: apps/v1
kind: Deployment
metadata:
  name: blink
spec:
  replicas: 3
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        apps: job-c1fd4a09-54dd-44cf-9e75-jobmanager
    spec:
      containers:
      - image: myonlyzzy/ks-guestbook-demo:0.2
        resources:
          requests:
            cpu: "1"
            memory: 400Mi
        name: guestbook-ui
        ports:
        - containerPort: 80
